site_name: Mimizou Room
site_description: 思考の速度と動物を愛するITエンジニアのサイト
site_url: https://mimizou.mamansoft.net
site_author: tadashi-aikawa
repo_name: tadashi-aikawa/mimizou-room
repo_url: https://github.com/tadashi-aikawa/mimizou-room
copyright: © 2020 tadashi-aikawa

theme:
  name: "material"
  palette:
    primary: "grey"
    accent: "deep purple"
  language: "ja"
  features:
    - tabs
  custom_dir: theme/
  logo: assets/images/mimizou.png
  favicon: assets/images/mimizou.png

plugins:
  - search:
      lang:
        - en
  - macros

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/tadashi-aikawa"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/Tadashi_MAMAN"

markdown_extensions:
  # ページ内リンク(もう使えない?)
  - wikilinks
  # スペース2つ付けなくても改行
  - nl2br
  # warningとか
  - admonition
  # コードハイライト
  - codehilite:
      guess_lang: false
  # 注釈
  - footnotes
  # URLやEmailアドレスの自動リンク
  - pymdownx.magiclink
  # キーボードの見た目をカッコヨクする
  - pymdownx.keys
  # ???で折りたたみ
  - pymdownx.details
  # admonitionの中でもcode fence blockを使えるように
  - pymdownx.superfences
  - toc:
      permalink: True
  # ===でタブ
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true


extra_css:
  - "css/custom.css"

google_analytics:
  - "UA-36444836-2"
  - "auto"
