site_name: Mimizou Room
site_description: 思考の速度と動物を愛するITエンジニアのサイト
site_url: https://mimizou.mamansoft.net
site_author: tadashi-aikawa
repo_name: tadashi-aikawa/mimizou-room
repo_url: https://github.com/tadashi-aikawa/mimizou-room
copyright: © 2019 tadashi-aikawa

theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'deep purple'
  language: 'ja'
  logo: https://avatars1.githubusercontent.com/u/9500018?s=460&v=4
  favicon: https://avatars1.githubusercontent.com/u/9500018?s=460&v=4
  feature:
    tabs: true


extra:
  search:
    language: 'en, ja'
  social:
    - type: 'github'
      link: 'https://github.com/tadashi-aikawa'
    - type: 'twitter'
      link: 'https://twitter.com/Tadashi_MAMAN'

markdown_extensions:
  # ページ内リンク(もう使えない?)
  - wikilinks
  # スペース2つ付けなくても改行
  - nl2br
  # warningとか
  - admonition
  # コードハイライト
  - codehilite:
      guess_lang: false
  # 注釈
  - footnotes
  # URLやEmailアドレスの自動リンク
  - pymdownx.magiclink
  # キーボードの見た目をカッコヨクする
  - pymdownx.keys
  # ???で折りたたみ
  - pymdownx.details
  # admonitionの中でもcode fence blockを使えるように
  - pymdownx.superfences
  - toc:
      permalink: True

extra_css:
    - 'css/custom.css'